### ISSUE TITLE
TODOs for Merging with alice Branch and Codebase Cleanup

### ISSUE THREAD

**Issue by Yaxuan-w** [Lind-Project/RawPOSIX#2]
## Description:

This issue is created to track the necessary tasks for merging the alice branch and performing general codebase cleanup.

### TODOs:

1. Merging with `alice` branch
- [x] Remove example_grate folder and replace it with fdtables.

2. Codebase Cleanup:
- [x] Delete unused code lines (commented-out lines), specifically in:
       - `interface`
       - `safeposix_rust`
      
3. Porting RustPOSIX Testsuite:
- [ ] Ensure the RustPOSIX testsuite is successfully ported: including troubleshooting -> fixing -> documentation for all kinds of changes and differences. I've already made some progress of this and documented on RawPOSIXIssueTrack on my own repo. Need to find a more efficient way for further collaboration.

**Comment by Yaxuan-w** [comment]
@ChinmayShringi Could you help with cleaning the codebase?

**Comment by Yaxuan-w** [comment]
### Progress Update

#### Cleanup:

@ChinmayShringi and I finished cleanup on `src/safeposix/syscalls` on PR #14 

Still need to do cleanups for `src/interface` and other files on `src/safeposix`

#### Porting newest fdtables:

I ported newest fdtables on PR #14
